name: Update README all day at 13:37

on:
  workflow_dispatch:
  schedule:
    # “At 13:37 on every day-of-week.”
    # - cron: '37 13 * * *'
    - cron: '26 21 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: 'The Force :rocket:'
          author_email: contact@arthurducept.fr
          force: false
          signoff: false
          message: ':memo: README.md updated by power of the Force! :rocket:'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}